### ISSUE TITLE
/v1/file/upload: Add validation to uploadMeta/updateMeta objects 

### ISSUE THREAD

**Issue by stewartie4** [0chain/blobber#100]
On an upload request to a blobber, there is currently only a presence check on the uploadMeta object; none of the contents of uploadMeta is validated.
This leads to hard to debug issues on subsequent commit requests:

- If actual_size and/or actual_hash is not present in uploadMeta on upload then the subsequent /v1/connection/commit call will always fail with an invalid write marker as the hash will always mismatch.
![image](https://user-images.githubusercontent.com/18306778/116796031-49531300-aad1-11eb-97c1-186060632654.png)

- if connection_id is not present in uploadMeta on upload then the subsequent commit will always fail with file not found, leaking the blobber internal file structure as part of the response (this leaks info to potential attackers)
![image](https://user-images.githubusercontent.com/18306778/116796029-41936e80-aad1-11eb-8511-3f01a54474f0.png)

- if filename and filepath is not present in uploadMeta on upload then upload will fail with file already exists 
![image](https://user-images.githubusercontent.com/18306778/116796066-9afb9d80-aad1-11eb-993b-88410e4221d2.png)

Suggested solution: 
- Add validation to uploadMeta/updateMeta objects making the following fields mandatory:
 actual_size
 actual_hash
 connection_id
 filename
 filepath
 And fail fast on the upload call.
- Ensure we aren't leaking filesystem info or similar back to the user in the event of an error on any endpoint

**Comment by andrenerd** [comment]
@stewartie4 please, review:
https://github.com/0chain/blobber/pull/106
