### ISSUE TITLE
Download File from one blobber only

### ISSUE THREAD

**Issue by Jayashsatolia403** [0chain/blobber#1014]
In rewards testing, we need to download the file from one blobber only. It does not matter if the file is complete or not. 

Conditions I am testing this for : 

Network : 2 blobbers | 2 validators | read_price 0.1ZCN

Allocation : 1 data | 1 parity

**Comment by lpoli** [comment]
As per the discussion with @Jayashsatolia403, the requirement was regarding reward distribution w.r.t readmarkers.
Currently we do not have feature in gosdk to download from specific blobber. Also it is time consuming to make it happen and given the fact that it will only be used for rewards testing.

Like we have conductor tests which makes use of build tag, we can have separate handler in blobber that handles an endpoint to insert readmarker to the blobber database.
We shall have an endpoint where we can post readmarker from a client(no need to upload/download any file) and an endpoint to get readmarker.

Note that a client will use single row in `read_markers` table and each readmarker's `read_counter` will get updated to `ReadCounter` field of `read_markers` table.

Similarly we can have command in zbox cli to insert readmarker and use build tag  to separate it out from normal build. In zbox user should be able to select blobber to send readmarker for. The arguments for the command shall be allocation id, blobber id, readCounter. 

I am not sure if we need to send PRs in both case.
