### ISSUE TITLE
Removing reduant X-Client-App-Id and X-Client-App-Key headers.

### ISSUE THREAD

**Issue by MurashovVen** [0chain/blobber#108]
Now, X-Client-App-Id and X-Client-App-Key are redundant after merging [PR 66](https://github.com/0chain/blobber/pull/66).
We can decide what we gonna do with it.

**Comment by MurashovVen** [comment]
Also, this feature was mentioned [there](https://github.com/0chain/blobber/issues/48).

**Comment by stewartie4** [comment]
I agree, the signature identifies the user now. 
The only case I can think of is the consumer of an auth ticket - is a signature used in those cases too?
If so then I don't see what purpose these serve now

**Comment by stewartie4** [comment]
The X-Client-App-Id header itself may still be needed in order to identify collaborators, especially if collaborator support is added to the endpoints listed in https://github.com/0chain/blobber/pull/66  
The presence and owner checks are redundant though as is the X-Client-App-Key

**Comment by cnlangzi** [comment]
X-Client-App-Id is different from X-Client-App-Key on request signature. id is client_id, key is client_public_key. so let's leave as they are.
