### ISSUE TITLE
Postgres docker hub image compromised

### ISSUE THREAD

**Issue by sculptex** [0chain/blobber#11]
As per https://github.com/docker-library/postgres/issues/664

A compromised docker image is being utilized.

It results in a flood attack as follows:-

##########################################################################
#               Netscan detected from host  x.x.x.x               #
##########################################################################

time                protocol src_ip src_port          dest_ip dest_port
---------------------------------------------------------------------------
Wed Oct 14 03:37:58 2020 TCP  x.x.x.x 56746 =>    172.16.4.103 5432 
Wed Oct 14 03:37:58 2020 TCP  x.x.x.x 43900 =>    172.16.4.104 5432 
Wed Oct 14 03:37:58 2020 TCP  x.x.x.x 41680 =>    172.16.4.105 5432 
Wed Oct 14 03:37:58 2020 TCP  x.x.x.x 57360 =>    172.16.4.107 5432 
Wed Oct 14 03:37:58 2020 TCP  x.x.x.x 37710 =>    172.16.4.108 5432 
Wed Oct 14 03:37:58 2020 TCP  x.x.x.x 48438 =>    172.16.4.109 5432
...

This requires immediate attention.

**Comment by KrishnaDeqode** [comment]
But we are using `postgres:11` image
In the attached link it says 11.2 is compromised, Which image we should use then?

**Comment by sculptex** [comment]
I am a total novice with docker so cannot confirm what work. One solution proposed is to "updated the docker compose file to bind the ports to 127.0.0.1 instead of 0.0.0.0" but there also links to problems with 12.4 where another proposal says solution is to build from source instead of using prebuilt image, I don't know what is feasible. The issue did not appear immediately so is also hard to diagnose

**Comment by sculptex** [comment]
![Screenshot at 2020-10-11 21-09-06](https://user-images.githubusercontent.com/12629448/96112432-801d5f00-0eda-11eb-93fa-f88b29ab60a6.png)
This was htop

**Comment by sculptex** [comment]
A potential solution has been posted on https://github.com/0chain/blobber/pull/12 so I will close this issue
