### ISSUE TITLE
Resume upload with chunk size

### ISSUE THREAD

**Issue by cnlangzi** [0chain/blobber#111]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Question

___
### Bug

___
### Requirement or improvement
It is frustrating for a user to upload a large file(eg. video) in single request if there is is loss of connectivity or change of connections from WiFi to Cellular or vice versa. The file should be split into smaller pieces(e.g 64KB), and upload them one by one. It can be resumed when any pieces was failure. This if very helpful. And it should be designed as default mode.

**Comment by guruhubb** [comment]
We could potentially use it, but is it an overkill and inefficient for what we want to do with sequenced upload stream?  We just need to add a sequence number like we do for downloads to the client. On the blobber side we need to acknowledge the sequence.

**Comment by cnlangzi** [comment]
It is implemented based on customer header `Upload-Length` and `Upload-Offset` . it should be liked a sequence https://tus.io/protocols/resumable-upload.html#statusurl . It seems be more flexible.

**Comment by guruhubb** [comment]
ok sure go ahead

**Comment by cnlangzi** [comment]
@guruhubb  I will double check, and find a workaround that should be backwards compatible for current gosdk/zboxcli

**Comment by cnlangzi** [comment]
it is fixed on https://github.com/0chain/blobber/pull/344
