### ISSUE TITLE
Clientpool for multiple allocations and read/write operations

### ISSUE THREAD

**Issue by andrenerd** [0chain/blobber#119]
blobber, payerID for read pool similar to payerID for write pool

**Comment by guruhubb** [comment]
@andrenerd @moldis we need to change the write/read pool into a single pool for simplicity and allow multiple payers to lock tokens. Need changes in storagesc, blobber, gosdk, and zboxcli. We also need to fold in the network locking tokens for free storage for user when they receive a freeStorage transaction as one of the payer for the pool.

**Comment by andrenerd** [comment]
@guruhubb 
could we spin off "read and write pools merging" discussion into a separate issue if appropriate?
and probably to start with it after payerID related changes. otherwise, imho, it could be messy.

**Comment by guruhubb** [comment]
Lets have a call on Slack with Artem to discuss this. Look at the delegate pool model setup for blobber. The payerID is legacy code (2018) which we need to move to delegate pool type architecture.  The read/write pools are both tied to allocation and blobbers, which remains as is, except there is one pool.

**Comment by andrenerd** [comment]
Closing it, as the proposed enhancements were partly implemented by this issue/pr:
https://github.com/0chain/blobber/issues/161

And partly overlay with another more broad client pool implementation issue. Btw, I personally gravitate to the view that client pool itself is an excessive enhancement. Read/Write pools does it job well.
