### ISSUE TITLE
Add encryption to grpc communication

### ISSUE THREAD

**Issue by shravanshetty1** [0chain/blobber#122]
Add TLS communication to our grpc client-server, gRPC has SSL/TLS integration and promotes the use of SSL/TLS to authenticate the server, and to encrypt all the data exchanged between the client and the server. 

### Problem
 By default DialOption{grpc.WithInsecure()} is used in example (point 6). As mention in docs you just need to replace [WithInsecure](https://pkg.go.dev/google.golang.org/grpc?utm_source=godoc#WithInsecure) with [transport creds](https://godoc.org/google.golang.org/grpc#WithTransportCredentials) for introducing tls in grpc-gateway

Solution example implementation see https://github.com/gogo/grpc-example

**Comment by shravanshetty1** [comment]
https://github.com/grpc/grpc-go/blob/master/Documentation/grpc-auth-support.md

**Comment by shravanshetty1** [comment]
@anish-squareops @m-s-a-c this needs to be handled by proxy like https

**Comment by kushthedude** [comment]
What are we aiming for here? Mutual-TLS or Server-side TLS?

**Comment by shravanshetty1** [comment]
We probably want whatever https is using. Some research on what industry is doing is needed.

**Comment by kushthedude** [comment]
> We probably want whatever https is using. Some research on what industry is doing is needed.

Didn't get you here, grpc communication would happen under the hood of the server, we can serve our grpc services over https.

**Comment by vitaliy-kuzmich** [comment]
test

**Comment by cnlangzi** [comment]
blobber hanlders are proxy by nginx in k8s. I don't think we need it on blobber side.
