### ISSUE TITLE
[FEATURE] Added mock servers for 0dns, sharders and miners

### ISSUE THREAD

**Issue by cnlangzi** [0chain/blobber#145]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question

___
### Bug

___
### Requirement or improvement
it is unnecessary to run in real blockchain network for blobber development. Because it is low efficient ,unstable and difficult in  local/dev blockchain network. Blobber only interacts with 0dns, sharders and miners by HTTP apis. so it should be easier and better to do them with mock servers instead of blockchain network.  But Integration testing must be done in real blockchain network.

**Comment by shravanshetty1** [comment]
I think the real issue is that creating local blockchain environment is complicated - creating mock server is just a solution to this problem.

I think it would just be easier to simplify the creation of local blockchain environment.

We can drastically simplify the environment setup by switching from docker-compose to kubernetes. Kubernetes cluster can be run locally using https://kind.sigs.k8s.io/. Currently we have to run several commands just to setup local environment and it only setups one service and not the entire blockchain - this can be solved by switching to kubernetes which is being used in prod.

We can debug the services easily using remote debugging - https://www.jetbrains.com/help/go/attach-to-running-go-processes-with-debugger.html#attach-to-a-process-in-the-docker-container

**Comment by guruhubb** [comment]
we already have k8s and use it for various automation, but k8 is bad for development. None of our core developers use it. Our blockchain repo is fairly easy to set up, just takes a bit of time first time around. But Dayi's point is different.

**Comment by cnlangzi** [comment]
I am newbie on 0chain. I know docker as well. 

But it is frustrating for me to setup local development environment. Because I don't know 0chain blockchain very well.

I was struggling to setup local one. It can't be fixed after I read all documents and shell scripts in repos. I have to read code for everything.  BTW: our document and shell scripts are not up to date :(

It was a small issue about hash on magic_block.json. It is real difficult to fix it for a me as newbie. 

I really appreciate for @bbist 's help. He helps me to fix it via remote desktop. But it takes him 1 hour. It is not good for he and me. 

In my opinion, it is not friendly for who wants to contribute form team or community . 

It maybe better to split developer into different teams
- blockchain developer
- HTTP/gRPC API developer
- client tool developer
- 
Only blockchain developer need to know full 0chain blockchain development like your guys. And a API and tool developer just knows programming languages(eg. go, .NET, nodejs, swift...etc), and is enough good to do many amazing tasks( eg. zboxcli, migration tool, sync tool....etc ) .

For now, I already can quick setup a devnet. But it is still not enough stable for testing and debugging. It maybe my hardware issue. devnet is running on my a small VM server instead of my mac.

**Comment by cnlangzi** [comment]
It is not a good solution to debug blobber and validator in docker. Because we have to build and restart docker if any code is updated. It is too slow to do it. docker is best solution to deploy it anywhere. But it is easier to develop and debug on local binary. `./dev.local/cli.sh` is added for it. It includes
- install `blobber_postgres` as shared database for all blobbers and validators
- initialize database `blobber_meta1`, `blobber_meta2` and `blobber_meta3` with `blobber_user1` , `blobber_user2` and `blobber_user3`
- start local blobber instances (of course, it is easy to debug it via .vscode/launch.json )
- start local validator instances  (of course, it is easy to debug it via .vscode/launch.json )
- clean : all data are saved on ./dev.local/data/blobber* . It is ignored in git as default.  You can feel free to play or remove it. git stats is always clean.

**Comment by cnlangzi** [comment]
It seems is linked to #170
