### ISSUE TITLE
[FEATURE] Add test coverage tracker

### ISSUE THREAD

**Issue by shravanshetty1** [0chain/blobber#151]
https://github.com/codecov/codecov-action
Will have to do some research

**Comment by stewartie4** [comment]
Sonarqube is also an option which also integrates well with lint ￼and GitHub to prevent merges of code with low coverage 

https://www.sonarqube.org

**Comment by shravanshetty1** [comment]
![Screenshot from 2021-05-24 12-16-44](https://user-images.githubusercontent.com/58299697/119307923-02001280-bc8a-11eb-8df9-6e2d44c93a25.png)
This should be added in the main README.
A tracker should also exist when PR's are being sent in

**Comment by cnlangzi** [comment]
add /.github/workflows/test.yml

```
name: Test
on:  push:    branches: [ main ]  pull_request:    branches: [ main ]
jobs:
  build:    runs-on: ubuntu-latest    steps:    - uses: actions/checkout@v2
    - name: Set up Go      uses: actions/setup-go@v2      with:        go-version: 1.15
    - name: cfg:testing      run: cd $GITHUB_WORKSPACE/cfg &amp;&amp; go test -race -coverprofile=coverage.txt -covermode=atomic        - name: cfg:Codecov      run: cd $GITHUB_WORKSPACE/cfg &amp;&amp; bash &lt;(curl -s https://codecov.io/bash)
    - name: fmt:testing      run: cd $GITHUB_WORKSPACE/fmt &amp;&amp; go test -race -coverprofile=coverage.txt -covermode=atomic        - name: fmt:Codecov      run: cd $GITHUB_WORKSPACE/fmt &amp;&amp; bash &lt;(curl -s https://codecov.io/bash)
```


and it can be shown by 
[![codecov](https://codecov.io/gh/0chain/blobber/branch/main/graph/badge.svg)](https://codecov.io/gh/0chain/blobber)

**Comment by cnlangzi** [comment]
@guruhubb You need to register ochain/blobber on https://codecov.io/ first.

**Comment by cnlangzi** [comment]
if it's ok. I will add this action quickly.

**Comment by guruhubb** [comment]
@cnlangzi go ahead.

**Comment by kushthedude** [comment]
Why not use the codecov gh-action?

**Comment by kushthedude** [comment]
ping @cnlangzi

**Comment by cnlangzi** [comment]
> ping @cnlangzi

@kushthedude  it is fine to change it with codecov action. Both of them should work properly.
