### ISSUE TITLE
Upgrade allocation payer-based logic

### ISSUE THREAD

**Issue by andrenerd** [0chain/blobber#161]
Cleanup and extend logic related to Allocation.PayerID field. Don't mess it with Read/WriteMarker.PayerID, they have different "nature".
The changes supposed to be used to implement freeStorage feature later too.

List of possible changes:
- Drop some legacy Allocation.PayerID-linked logic, that was used by "Repair" features that were completely removed. 
https://github.com/0chain/blobber/commit/31339e9997cf520733343153787c3a55431d6115

- Make Allocation.PayerID independent value, that, if provided, should indicate, that _all_ operations for the Allocation are payed by this payer by default.

- The could be implemented exceptions, only if another Payer explicitly indicated. for example, by "rx_pay" flag. It's could be important to note, that Allocation.PayerID is not de-facto used for "rx-pay" logic, even though a comment in the current Allocation struct declaration tells that!

Outcomes: 
The changes let to set PayerID value on allocation creation for the freeStorage scenario. The value could set to Owner. Or possibly another user, if it will be required by new use cases.

**Comment by andrenerd** [comment]
Notes for the future:
- former "misused" PayerID moved to RepairerID.
- RepairerID is used for access checking and has nothing with payments or PayerID. 
- RepairerID has been used to store value for (blobber?) node id. It's not client id. Don't be confused by the legacy code.

**Comment by guruhubb** [comment]
@MurashovVen please comment on the repair flow, because you were working on the add/drop blobber and we need to make sure the changes do not affect your PR later.

**Comment by MurashovVen** [comment]
I have not started the implementation of add/drop function, so there should be no conflicts here.

**Comment by guruhubb** [comment]
I still don't have an answer for this yet. @Sriep can you construct a UML flow for read and write pools, and how multiple payers fit in.
a. Is the read pool associated with the user wallet?
b. For rx_pay do the blobbers get tokens from the receiver read pool?
c. Is the user only one that can lock tokens for their read pool or is it open to other folks?
d. If there are multiple pools, which tokens are moved to the blobber wallets? Is the earliest expired read pool?

**Comment by andrenerd** [comment]
a) sort of. read pool is associated with user and contains numerous (read) allocation pools. each one of them is "linked" to wallet (potentially, any). who (from whom wallet) "funded" an allocation pool doesn't matter too much. except the case when non used funds are "returned" (ie "released").

b) rx_pay: yes, they do. it's a possible implemented option. btw, auth token should be also provided for the case.

c) potentially to any, as the data structures and methods make it possible (more in point A). but not sure the existing interfaces (incl. zboxcil) lets to do it.

d) yes, the earliest expired read allocation pools goes first:
https://github.com/0chain/0chain/blob/6035fbed7861047a074042be391390ff87bb82b8/code/go/0chain.net/smartcontract/storagesc/allocation_pool.go#L245

**Comment by guruhubb** [comment]
Thanks @andrenerd. So a) unused tokens can be unlocked back to the payer.  @Sriep go ahead and have functions in gosdk/zboxcli to put tokens into an user's read pool and use the same mechanism as newallocation and payerID to lock tokens into user's write pool . Once done, I’ll let Artem know this so that he can have 0box server put tokens in read/write pool of any subscriber.  I assume that when they expire and are unlocked, they come back to the payer.

**Comment by Sriep** [comment]
Continued in issue https://github.com/0chain/0chain/issues/379.
