### ISSUE TITLE
Add .proto file linter and formatter

### ISSUE THREAD

**Issue by shravanshetty1** [0chain/blobber#181]

**Comment by shravanshetty1** [comment]
Requires research

**Comment by kushthedude** [comment]
Let's move out all of our proto files to https://github.com/bufbuild/buf, it is the most reliable and efficient way to work with protobufs. Removes the hectic of managing protoc client versions as well as have inbuilt more than 50 best practices for proto. We can even integrate it into our Github actions to ensure best practices during developing the grpc endpoints.

**Comment by shravanshetty1** [comment]
https://github.com/0chain/blobber/issues/43

**Comment by kushthedude** [comment]
Can you assign me this?

**Comment by kushthedude** [comment]
Also, can you assign me the buf issue?

**Comment by shravanshetty1** [comment]
Not sure why but your not in the list of people i can assign in the other issue. If you comment on that issue - you may get indexed.
