### ISSUE TITLE
Seems even I shutdown blobber, I still can see it in ls-blobbers

### ISSUE THREAD

**Issue by moldis** [0chain/blobber#208]
After deployed on my local env single blobber, I was able to fetch it in `zbox ls-blobbers`. But, after I shutdown I still can see it in `zbox ls-blobbers`.

**Comment by cnlangzi** [comment]
it should be fixed on https://github.com/0chain/zboxcli/pull/40

**Comment by moldis** [comment]
@cnlangzi Issue is in explorer also and as I know explorer not using zboxcli method

**Comment by chauchausoup** [comment]
As I just tested in nine network explorer I could see filtered blobbers list as shown in the screenshot below.
Here `http://171.240.141.17:5051` blobber's last health check was more than hours ago so its is not shown or say filtered in the UI.
![Screenshot from 2021-06-14 22-34-37](https://user-images.githubusercontent.com/34975245/121929484-f96a9b80-cd60-11eb-9e1e-3d1dd3994b03.png)

**Comment by guruhubb** [comment]
@andrenerd is this resolved with your recent update?

**Comment by andrenerd** [comment]
@guruhubb nope, it's not related to the update.

essentially, there is no issue. the system continues to keep blobbers on the list, even if they don't send health check signals anymore, ie turned off or so.

so, seeing turned of blobbers is ok, according to the current implementation. surely the rules could be updated to filter them out or so. if it's not needed, the issues is supposed to be closed.

ps.
by the way, "turned off" blobbers are not taken in account when new allocation is created. as the health check information is used to filter them out in that particular case:
https://github.com/0chain/0chain/blob/42a5270a0d62c08e9af2c09a501301d57008898b/code/go/0chain.net/smartcontract/storagesc/blobber.go#L119

**Comment by guruhubb** [comment]
@moldis add a health check filter for ls-blobber in gosdk and have an option `--all` to include non-active blobbers.

**Comment by chauchausoup** [comment]
@guruhubb this should work.
https://github.com/0chain/zboxcli/pull/40
