### ISSUE TITLE
gorm seems has a bug on time with timezone

### ISSUE THREAD

**Issue by cnlangzi** [0chain/blobber#219]
The connection can't be deleted.  

We have two `timezone` now. One is postgres's , another is golang's.

In postgres, column may have a default value with `now()` (eg. allocation_connections.create_at). The timezone is set with `postgres` timezone. 
In golang, we may upload some column with `time.Now()` (eg. allocation_connections.update_at). the timezone is set with `golang` timezone(it also is server's timezone)

there are two solutions:

- should all time should be converted with a default timezone on postgres? if yes, what is the timezone . It is `UTC` ?
- should `globalization feature` be implemented? time should be converted in different timezones automatically.

`2021-06-21 03:06:43.899692 +0000 UTC` >  `2021-06-21 10:20:23.844087 +0800 CST m=-3564.945252206`

<img width="951" alt="Screen Shot 2021-06-21 at 11 24 21 AM" src="https://user-images.githubusercontent.com/347651/122703241-b2f6ce80-d283-11eb-9776-833416dd69e7.png">
<img width="1200" alt="Screen Shot 2021-06-21 at 11 25 47 AM" src="https://user-images.githubusercontent.com/347651/122703246-b4c09200-d283-11eb-90e4-7dff2f1114db.png">

**Comment by andrenerd** [comment]
Imho, we should stick to UTC only. So the first proposed approach to be implemented.

ps. as you have already tracked the issue down and proposed the solution, could you assigned the issue to yourself. thanks.

**Comment by cnlangzi** [comment]
@andrenerd OK. leave it with me. thanks.

**Comment by cnlangzi** [comment]
it is fixed on https://github.com/0chain/blobber/pull/344
