### ISSUE TITLE
object_opearation_handler.go: rx_pay in Downloadfile plus others

### ISSUE THREAD

**Issue by Sriep** [0chain/blobber#236]
some problems with object_operation_handler.go. 

1. DownloadFile: The rx_pay is used to indicate that a read action down using an auth ticket is paid by the client not the allocation owner. It is not used for collaborators. Currently, this is round the wrong way. 
2. DownloadFile: WhoPaysForReads should not effect users using auth tickets.
3. GetFileMeta does not validate check for collaborator or owner.
4. GetFileStats neither collaborator nor auth ticket holder can get file stats.
5. There should also be unit tests for this file.

**Comment by Sriep** [comment]
rx_pay issue fixed in https://github.com/0chain/blobber/pull/245

**Comment by kushthedude** [comment]
@Sriep is this fixed?

**Comment by Sriep** [comment]
1 is fixed. 
2. Might still be an issue? Do we need this block https://github.com/0chain/blobber/blob/staging/code/go/0chain.net/blobbercore/handler/object_operation_handler.go#L292
3. and 4. As far as I can tell user validation is still missing. We could test.
5 A tests added for DownloadFile, others would be nice but probably not urgent.

**Comment by cnlangzi** [comment]
@peterlimg  it might be fixed by https://github.com/0chain/blobber/pull/717. let's leave it with @lpoli . @lpoli  is it right?

**Comment by lpoli** [comment]
@cnlangzi It will fix. I've to some work left there.
