### ISSUE TITLE
Not all handler function verifies client signature

### ISSUE THREAD

**Issue by lpoli** [0chain/blobber#239]
ObjectTree, ObjectPath, etc. have all implemented signature verification but following handler does not require client signature.
1. _/v1/file/meta/{allocation}_
2. _/v1/file/list/{allocation}_

There maybe other requests handler that does not require client signature.

**Comment by kushthedude** [comment]
What is expected scene here? Should we have a check for signature header_key in the request which implements signature verification? I can cover this for the grpc handlers.
cc: @lpoli @guruhubb

**Comment by stewartie4** [comment]
@kushthedude Any endpoint/handler that queries an allocation should be signed by either the allocation owner or a registered collaborator 
So in the cases above, yes those should be signed too - see this issue https://github.com/0chain/blobber/issues/48 for context

**Comment by kushthedude** [comment]
Thanks Got it @stewartie4 , the issue title should have been more descriptive, anyways since I am already revamping the HTTP APIs I can pick this up & add the owner verification in both the methods.

**Comment by shaktals** [comment]
This probably clarifies [this error](https://github.com/0chain/block-explorer/issues/220#issuecomment-868814716) we were facing on `block-explorer`. It seems like we need to add the `X-App-Client-Signature' header to those calls. As of now, all signature generation for API calls are being handled by `js-client-sdk`. But only 3 methods are using it: `postShareInfo`, `deleteSharedObject` and `getShareInfo`. But once we have the APIs behavior sorted out, we can fix the helper libs and clients accordingly.

@kushthedude I've been wanting to help out on the backend, if you haven't picked this up yet, I'd have fun doing it.

After it's done we have to remember updating the docs, by the way.

**Comment by moldis** [comment]
cc @kushthedude

**Comment by cnlangzi** [comment]
@stewartie4  it should be fixed on latest staging. could you help to double check it? if it is fixed, please close this issue. thanks.

**Comment by stewartie4** [comment]
looks good to me 
<img width="397" alt="image" src="https://user-images.githubusercontent.com/18306778/143009686-388ce268-2938-4f86-bcde-799bee163767.png">
