### ISSUE TITLE
Revamp integration_tests to unit tests

### ISSUE THREAD

**Issue by kushthedude** [0chain/blobber#253]
Unit tests are wrongly suffixed as integration_tests. 
## Tasks
- Refactor all the integration_tests into unit tests.
- Modify the CI & test script to run unit_tests.
- Make sure the tests don't break.

**Comment by lpoli** [comment]
Integration tests has purpose of testing if grpc has well integrated with the blobber. Every integration has tests against grpc service. This cannot be treated as unit test.

Recently unit tests are separated with `!integration` tag, which separates them from integration testing
