### ISSUE TITLE
grpc-gateway: throw away http_handlers & make sure gRPC handlers take care of all the logic

### ISSUE THREAD

**Issue by kushthedude** [0chain/blobber#254]
#### Problem
If we want to have gRPC performance then we shouldn’t use http communication through the grpc services. Rn, we are just using grpc as an extra abstract layer over our http handlers, our performance load is much with this
`gRPC Request->HTTP Request->HTTP Response->gRPC Response` this is our current flow in the blobber.

#### Consequences
- We are using REST under the name of gRPC by constructing HTTP request & passing to HTTP handlers.
- We are not utilising the throughput of complete gRPC performance.
- Degraded performance & invalid use of grpc-gateway ecosystem.

#### Proposed Solution
- Start developing on a new branch grpc_protocal where we can start ripping off HTTP handlers one by one & will only have grpc streaming for all sort of communication b/w blobber & gosdk.

**Comment by cnlangzi** [comment]
grpc protocol doesn't work on wasm. I think we don't need this feature yet. we can raise new issue if it is necessary in future.
