### ISSUE TITLE
[FEATURE] Golangci-lint: Enforce stricter rule checking & linting for blobber

### ISSUE THREAD

**Issue by kushthedude** [0chain/blobber#262]
Problem:
Needless to mention the code quality is too low in the blobber without ensuring the golang standard checks like pascalCase naming, error handling, static checks & more.

Solution:
We already have golangci-lint setup for our codebase but here is the problem by default the golangci-lint only runs dead code check & nothing more. We need to set up a configuration file assuming what sort of checks would help us in maintaining an awesome code style. I have worked upon a configuration file that would be suitable for the stage blobber is at right now.

**Comment by cnlangzi** [comment]
it is done https://github.com/0chain/blobber/blob/2562e810b077830d4a9deab9a0304708800dd708/.github/workflows/tests.yml#L39
