### ISSUE TITLE
Gorm transaction variable limiting power of Go language.

### ISSUE THREAD

**Issue by lpoli** [0chain/blobber#268]
This may not be major issue but I came across it while working with Object Tree pagination. When paginating we need certain number of rows as well as total rows without `limit` condition i.e. total rows count. So this would require two SQL  queries to run: One for limited number of rows and other to count total number of rows.

So instead of running two SQL queries sequentially we can use two go routines and make this process faster. But since *gorm.DB variable is put in `context value` by beginning a transaction: `tx := db.Begin()` this cannot be used in go routines. This transaction has been used in whole request handler and used in `WithReadOnlyConnection`, etc. to rollback or commit the transaction.

I tried to create new Session variable from `tx` but once it is generated with `db.Begin` it not [thread safe to use in go routines](https://gorm.io/docs/method_chaining.html#Method-Chain-Safety-Goroutine-Safety).

**Comment by kushthedude** [comment]
> All Chain Methods will clone and create a new DB object (shares one connection pool), GORM is safe for concurrent use by multiple goroutines.

⬆️

**Comment by lpoli** [comment]
The point is its not safe if you do `db = db.Begin()`
For other cases it will create New Session Method and they are safe for concurrent use

**Comment by lpoli** [comment]
To get a count of rows we can create new transaction and use it.
