### ISSUE TITLE
connection_write_error received periodically when calling delete/rename

### ISSUE THREAD

**Issue by stewartie4** [0chain/blobber#293]
Multiple blobbers are experiencing this issue periodically across multiple networks.

Given a rename request to /v1/file/rename such as 
![image](https://user-images.githubusercontent.com/18306778/128356654-1583e059-9c1d-4a8a-b6e0-8787b57ca4de.png)

Or a delete request to /v1/file/upload such as 
![image](https://user-images.githubusercontent.com/18306778/128356722-94e24534-a7b1-497e-8eb5-58a4b6ea3e03.png)

We are periodically getting returned the following 400 response:
![image](https://user-images.githubusercontent.com/18306778/128356869-61ab371b-cd47-4331-8718-8d7f3d92aa0f.png)

{
  "code": "connection_write_error",
  "error": "connection_write_error: Error writing the connection meta data"
}

This is periodic - the exact same request will pass after a few retries.

See: https://0chain.github.io/0chain/dev/2021-08-04_23.22.14/index.html for details

**Comment by stewartie4** [comment]
This no longer seems to be periodic and is filing consistently 
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/18306778/130488652-9353b1c4-9457-4da8-bc70-05fe75c761c7.png">

**Comment by kushthedude** [comment]
This is fixed in grpc deployment @stewartie4 , we will soon make grpc as the default branch so this is gonna be fixed as well

**Comment by stewartie4** [comment]
Nice! What was the issue?

**Comment by kushthedude** [comment]
I guess its this PR only https://github.com/0chain/blobber/pull/273 . I didnt merge this PR into my grpc because it doesn't had any unit tests, I made a review on to add unit-tests but seemed like change was too trivial for author. So I left it until the unit tests for the change were added.

**Comment by kushthedude** [comment]
The PR was reverted so shall the issue too, do check again if it occuers
