### ISSUE TITLE
Bug while checking challenge

### ISSUE THREAD

**Issue by lpoli** [0chain/blobber#298]
This line creates panic error (and has created in local):
https://github.com/0chain/blobber/blob/master/code/go/0chain.net/blobbercore/challenge/worker.go#L232

When first condition is false with latestChallenge to nil and length of previous challenge id not being 0 then it will panic in second condition.
Condition checking should be refactored.

**Comment by cnlangzi** [comment]
leave it with me. I am working on challenge issues. I will double check and fix it.

**Comment by cnlangzi** [comment]
It has been fixed on `ChunkedUploaded` pr
