### ISSUE TITLE
Blobber should timeout requests that have not been responded to in over 10 seconds

### ISSUE THREAD

**Issue by shravanshetty1** [0chain/blobber#30]

**Comment by andrenerd** [comment]
@shravanshetty1 
Let me to clarify: to timeout "incoming" requests to Blobber or "outcoming" requests from Blobber to Sharders or other services?

If Blobber timeouts "incoming" requests, should this "timeout" rule be applied to all the request handlers? or specific ones?:
https://github.com/0chain/blobber/blob/master/code/go/0chain.net/blobbercore/handler/handler.go#L30

PS. I guess, there is an example of such restriction, is this what you mean?
```
func ReferencePathHandler(ctx context.Context, r *http.Request) (interface{}, error) {
	ctx, _ = context.WithTimeout(ctx, time.Second*10)
	ctx = setupHandlerContext(ctx, r)
...
```
https://github.com/0chain/blobber/blob/master/code/go/0chain.net/blobbercore/handler/handler.go#L204

**Comment by shravanshetty1** [comment]
Yes, it should be for all handlers not just one. This should be a grpc middleware for the new api.

**Comment by shravanshetty1** [comment]
@andrenerd all the grpc issues are low prio, make sure @guruhubb knows your working on this. There maybe other issues that are in prio right now.

**Comment by andrenerd** [comment]
@shravanshetty1 
There is a question: should it be an interceptor or we can just set timeouts in the config?

In case of config, here is a timeout param per method (in seconds):
```
google.protobuf.Duration timeout = 3;
```

In case of an interceptor, here is a snippet:
```
func unaryTimeoutInterceptor() grpc.UnaryServerInterceptor {
  return func(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error) {
    deadline := time.Now().Add(time.Duration(TIMEOUT_SECOND * time.Second)
    ctx, cancel := context.WithDeadline(ctx, deadline)

    res, err := handler(ctx, req)
    return res, err
  }
}
```

NB.  I guess there is no need to rollback anything when deadline is overdue and DEADLINE_EXCEEDED error returned, as your "unaryDatabaseTransactionInjector" interceptor already does it?

PS. I know that it's a low-prio issue, but it was assigned to me to be completed soon.

**Comment by shravanshetty1** [comment]
> @shravanshetty1
> There is a question: should it be an interceptor or we can just set timeouts in the config?

Its your call but, the interceptor looks better to me.

Also, yes there should be no reason to rollback since there is another middleware that does that.
