### ISSUE TITLE
/v1/file/referencepath/{allocation} getting stuck on invalid allocation id and on bad filepath

### ISSUE THREAD

**Issue by shravanshetty1** [0chain/blobber#31]

**Comment by MurashovVen** [comment]
@shravanshetty1, I am working on this problem, could you please describe the error in more detail?

**Comment by shravanshetty1** [comment]
https://github.com/0chain/0proxy/issues/1

**Comment by Sriep** [comment]
Merged https://github.com/0chain/blobber/pull/50 so closing issue
