### ISSUE TITLE
Until first file upload allocation information, etc. not created.

### ISSUE THREAD

**Issue by lpoli** [0chain/blobber#317]
`zbox newallocation --lock 0.5` stores allocation.txt file with allocation id in it.
After this if we do `zbox list --remotepath / --allocation $alloc` then it shows `{"code":"invalid_parameters","error":"invalid_parameters: Invalid allocation id passed.verify_allocation: verifying allocation transaction error: record not found"}`. 

When checking into the blobber allocations table then respective allocation_id is not created.
What I was expecting was allocation information was stored when allocation is created and first row in `reference_objects` and likewise table to have metadata for root dir `/`.

**Comment by cnlangzi** [comment]
see detail on https://0chain.slack.com/archives/G014PQ61WNT/p1629885501118000

**Comment by cnlangzi** [comment]
@iamrz1 try to sync allocation from chain if it doesn't exists on postgres

**Comment by cnlangzi** [comment]
@princeparmar  please work on this issue.

**Comment by princeparmar** [comment]
@cnlangzi this is resolved it is not giving error now.
0chain-core-sdk [INFO]   2021/11/23 10:37:46.575452 wallet.go:291: ******* Wallet SDK Version:v1.2.87 *******
0box-sdk        [INFO]   2021/11/23 10:37:46.575525 sdk.go:72: ******* Storage SDK Version: v1.2.87 *******
0chain-core-sdk [INFO]   2021/11/23 10:37:46.576527 wallet.go:402: *******  Wallet SDK Version:v1.2.87 *******
0box-sdk        [DEBUG]  2021/11/23 10:37:46.577684 networkworker.go:103: Get network result:{"miners":["http://198.18.0.71:7071","http://198.18.0.72:7072","http://198.18.0.74:7074","http://198.18.0.73:7073"],"sharders":["http://198.18.0.81:7171","http://198.18.0.82:7172"]}
0box-sdk        [DEBUG]  2021/11/23 10:37:52.981452 listworker.go:111: List result:
0box-sdk        [DEBUG]  2021/11/23 10:37:53.331963 listworker.go:111: List result:
  TYPE | NAME | PATH | SIZE | NUM BLOCKS | LOOKUP HASH | IS ENCRYPTED | DOWNLOADS PAYER  
-------+------+------+------+------------+-------------+--------------+------------------
