### ISSUE TITLE
Security: Some file metadata endpoints can be queried without a signature

### ISSUE THREAD

**Issue by stewartie4** [0chain/blobber#327]
Similar to https://github.com/0chain/blobber/issues/48
The following endpoints can be queried with no authentication:
/v1/file/meta
/v1/file/list
Potentially leaking file metadata to anyone with the allocation id 

Solution:
Add X-App-Client-Signature header to the endpoints above as in https://github.com/0chain/blobber/issues/48
The signature will be generated on the client by BLS signing the hash of the allocation id
Possible clients that will need updated 
-Go SDK
-JS SDK
-0CLI
-Block-explorer

**Comment by cnlangzi** [comment]
the same issue on https://github.com/0chain/blobber/issues/239

**Comment by cnlangzi** [comment]
@Agaber90 please move all signature code to a middleware as https://github.com/0chain/blobber/blob/staging/code/go/0chain.net/blobbercore/handler/handler_middlewares.go

**Comment by Agaber90** [comment]
@cnlangzi  Sure

**Comment by iamrz1** [comment]
I went through the code, and found that the some APIs (about 12) perform signature verification on their own. We  can implement a middleware that can perform this specific task. Then we can just add the middleware to whichever API that needs to perform this check.
I have added a middleware in https://github.com/0chain/blobber/pull/394, please take a look and let me know what you think.
