### ISSUE TITLE
createDir: Incorrect values are saved in reference_objects and break challenge

### ISSUE THREAD

**Issue by cnlangzi** [0chain/blobber#329]
https://github.com/0chain/blobber/blob/7370c1e346733c3a31285bd0e75be1a87796c2ab/code/go/0chain.net/blobbercore/allocation/newfilechange.go#L89

It should be 

```
newDir.ActualFileSize = 0
newDir.Size = 0
newDir.NumBlocks = 0
````

Because it is new empty directory.

**Comment by cnlangzi** [comment]
`CalculateHash` should be updated too. An empty directory break LastWriteMarker on blockchain if there is no any transaction is committed to blockchain. Challenge is broken too.

https://github.com/0chain/blobber/pull/190#issuecomment-868163476

**Comment by cnlangzi** [comment]
after code review, it is completed wrong to create directory directly on local file system

https://github.com/0chain/blobber/blob/0c5de39b4adfa5b975a1b7e04a40c903c7726273/code/go/0chain.net/blobbercore/filestore/fs_store.go#L184

**Comment by moldis** [comment]
PR already in review
