### ISSUE TITLE
on_cloud field in /file/meta shows false despite committing it to the chain.

### ISSUE THREAD

**Issue by krishnemd** [0chain/blobber#338]
On severall CLI attempts on commiting the meta to blockchain while upoading the file and even explicitly commiting the meta to chain I can see no **on_cloud** field being updated to true.

It is also related to the explorer issue [#335]( https://github.com/0chain/block-explorer/issues/335)

**Comment by cnlangzi** [comment]
@chauchausoup on_cloud is designed for other feature , not for committing file to chain. It is updated in background worker `startMoveColdDataToCloud`. if it is true, it means file has been moved to minio cloud storage instead local disk .

**Comment by krishnemd** [comment]
As per our Slack convo write_marker is correct field for Blockchain aware instead of on_cloud. 

Dayi Chen  1 day ago
it should be write_marker.status

Dayi Chen  1 day ago
const (
    Accepted  WriteMarkerStatus = 0
    Committed WriteMarkerStatus = 1
    Failed    WriteMarkerStatus = 2
)
Regarding further implementation @cnlangzi is checking on it.
