### ISSUE TITLE
downloadFile possable security issue.

### ISSUE THREAD

**Issue by Sriep** [0chain/blobber#340]
Downloading a file works as follows.

1. zbox -> gosdk call to downloadFile.
2. downloadFile processes request. Returns file and adds a `read-redeem` item to the `read_redeems` SQL table, incrementing the count and setting redeem to true. It also checks, with `0chain/getReadPoolAllocBlobberStat`, that  there are enough funds in the appropriate read pool.
3. A work thread polls the `read_redeems` table for reads that need to be redded. Finds the download above.
4. Sends a `read_redeem` transaction to 0chain, which charges the appropriate read pool.

The problem with this process is if (4) fails as in https://github.com/0chain/gosdk/issues/246. Then an error is returned and no read pool is charged. However, the file has already been sent to the client. So they got it for free. Since `downloadFile` worked there is no obvious error returned anywhere, just logged in 0chain, so it is easy to overlook.

The 1->4 process means that if someone can work out a way of making `blobber\downloadFile` succeed while `0chain\read-redeem` fails, then they have a way of getting free downloads. Fixing https://github.com/0chain/gosdk/issues/246 will close one loophole, but can, or sould, we rely on there not being others?

**Comment by moldis** [comment]
cc @kushthedude

**Comment by lpoli** [comment]
I don't think this is a problem.
Before returning data, ReadMarker is validated, read pool fund is checked and later on it is redeemed. The blobber should redeem it within lock period. The client's token is locked in ReadPool and blobber will have some time to redeem read token.
If some error occurred then it should not be because client were able to tweak the process, rather other issues like network issue, critical bug in smart contract, etc.

**Comment by Sriep** [comment]
It is probably ok to keep this loophole around unless it actually becomes a problem  Fixing it at the moment might take more effort than it's worth. Still I think we should be aware of the danger.

**Comment by lpoli** [comment]
> 

Client cannot tweak the process.

**Comment by lpoli** [comment]
> I don't think this is a problem. Before returning data, ReadMarker is validated, read pool fund is checked and later on it is redeemed. The blobber should redeem it within lock period. The client's token is locked in ReadPool and blobber will have some time to redeem read token. If some error occurred then it should not be because client were able to tweak the process, rather other issues like network issue, critical bug in smart contract, etc.

@guruhubb client cannot tweak the process. I think this issue can be closed

**Comment by Sriep** [comment]
```
I don't think this is a problem.
Before returning data, ReadMarker is validated, read pool fund is checked and later on it is redeemed. The blobber should redeem it within lock period. The client's token is locked in ReadPool and blobber will have some time to redeem read token.
If some error occurred then it should not be because client were able to tweak the process, rather other issues like network issue, critical bug in smart contract, etc.
```
The problem was that the read_redeem and the download were done on separate parallel threads. So some data gets downloaded during the read_redeem transaction and before read_redeem fails, if it fails. I have not tested recently to see if this is still happeninging.

**Comment by lpoli** [comment]
I've not seen it being parallel operation.
But later on we have to use go routines to make reads faster, but also wait for pre-read redeeming.

@Sriep I assure you that we can close this issue for your above concerns
