### ISSUE TITLE
fix `make lint`

### ISSUE THREAD

**Issue by mallochine** [0chain/blobber#38]
Steps to repro:
1. `make lint` fails

You might need to install golangci-lint, follow instructions here: https://golangci-lint.run/usage/install/

make sure the $GOPATH/bin is in your $PATH.

**Comment by satchinjoshi** [comment]
@mallochine  it is only being installed GitHub action https://github.com/0chain/blobber/blob/master/.github/workflows/ci.yml#L33-L38

**Comment by mallochine** [comment]
The issue are lint errors.

In order to debug and fix lint errors locally on your dev environment instead of uploading to Github Actions every time, you might need to install golangci-lint

**Comment by Sriep** [comment]
We need to use something like https://github.com/0chain/0chain/pull/184 to add a GitHub action 
to pull request, that fails if the pull increases lint errors. 

If you want to run `golangci-lint` locally, you need to install it locally. I don't think there is any expectation of `make lint` working if the prerequisites are not present.  If that's confusing people may be an explanation and a link to [golangci-lint](https://github.com/golangci/golangci-lint) could be added somewhere.

**Comment by shravanshetty1** [comment]
Lint errors have been resolved with https://github.com/0chain/blobber/issues/84
