### ISSUE TITLE
build tag is missing on home page

### ISSUE THREAD

**Issue by cnlangzi** [0chain/blobber#397]
please fix it like sharder https://huawei.0chain.net/sharder02/_diagnostics

<img width="1113" alt="Screen Shot 2021-10-20 at 10 13 09" src="https://user-images.githubusercontent.com/347651/138016752-7195c1b5-696d-4853-9f2d-58bbe595ca7b.png">

**Comment by iamrz1** [comment]
I am not sure why this happens. Dockerfile get the build tag from the shel, so the tag should be available in the binary. Is there any similar for on any other repo that I can look at?

**Comment by cnlangzi** [comment]
> I am not sure why this happens. Dockerfile get the build tag from the shel, so the tag should be available in the binary. Is there any similar for on any other repo that I can look at?

sharder/miner/0dns have build tag too

**Comment by iamrz1** [comment]
I believe I have isolated the issue. 0chain/0chain repo and 0chain/blobber repo have different package architecture with go mod definition located in different location. However docker images from 0chain/blobber assumes the same architecture as 0chain/0chain to set build tags.
I have added a PR that addresses this by changing the path to build tag variable.
