### ISSUE TITLE
add conductor tests and enable it in github action

### ISSUE THREAD

**Issue by cnlangzi** [0chain/blobber#398]
can you work with @Roman and @Mohd Shahnawaz on the /conductor tests for blobber to get them as part of ci/cd.  https://github.com/0chain/0chain/tree/master/docker.local/config conductor.blobber-1.yaml, blobber-2 and you can run this and see for yourself. And if you want to add new cases please go ahead. (

please work with @Anish Gupta   @m-s-a-c  and  @stewartie4   on this once you set it up because they will be stage it in their ci/cd pipeline, and we need to provide reports and either mark it as pass/fail

**Comment by stewartie4** [comment]
we'll be adding conductor tests to the system tests pipeline?
remind me what these tests do vs regular system tests? these are sad/error path right?

**Comment by cnlangzi** [comment]
@Rizary  please checks and works with @stewartie4 . I don't have chance to check conductor tests @guruhubb mentioned

**Comment by rizary** [comment]
@stewartie4 conductor is like an RPC server for integration tests. It is automated according to the config specified in the 0chain/0chain repository. 

The conducter requires the nodes to be built first so it can run the test against the running nodes. The test conducted based on the config yaml that use a test suite.

**Comment by service-0chain** [comment]
working on same as --> https://github.com/0chain/blobber/issues/653
