### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by Sriep** [0chain/blobber#405]
The instructions in the [readme.md](https://github.com/0chain/blobber#building-and-starting-the-nodes) no longer work.This should be updated to explain how to run blobbers locally.

In particular
```bash
./docker.local/bin/build.blobber.base.sh && ./docker.local/bin/build.blobber.sh && ./docker.local/bin/build.validator.sh
```
`build.blobber.base.sh` no longer exists. Running `build.base.sh` instead failed when I tried.

**Comment by hm90121** [comment]
Closing this one @cnlangzi @Sriep  review the readme changes here 
https://github.com/0chain/blobber/pull/410
