### ISSUE TITLE
available_after param for /share option (private share only)

### ISSUE THREAD

**Issue by moldis** [0chain/blobber#439]
- Add new param available_after for private share, i.e Yeah but the use case is a bit different where people can create private NFTs and have a timelock. Would be something like “Elon Musk encrypted some form of data into an NFT and only after time XY the content will be viewable by the holder of the NFT” or “every holder of the NFT can open the encrypted content”.

example: `zbox share --allocation $alloc --remotepath /yolo/6.png --clientid $clientid --encryptionpublickey $enc_key --available_after 1637565245000`

If users whose file is shared with trying to download file with auth_ticket and the date is less than available_after - it should reject this download.

Relevant unit-tests and system_tests should be added.

**Comment by rizary** [comment]
the gosdk PR change to here: https://github.com/0chain/gosdk/pull/331

**Comment by cnlangzi** [comment]
it is fixed on #600
