### ISSUE TITLE
duplicate dir creation is not giving any error

### ISSUE THREAD

**Issue by princeparmar** [0chain/blobber#441]
/zbox createdir --allocation 4157af127d56077124753022f00cf84fb09df87f66d6bc46f9a61a27d45ff851 --dirname test

if we execute createdir comand with same dir name then in database instead of giving an error it creates duplicate entries.

test     | /test                 | 4157af127d56077124753022f00cf84fb09df87f66d6bc46f9a61a27d45ff851
 test     | /test                 | 4157af127d56077124753022f00cf84fb09df87f66d6bc46f9a61a27d45ff851
 test     | /test                 | 4157af127d56077124753022f00cf84fb09df87f66d6bc46f9a61a27d45ff851
 test     | /test                 | 4157af127d56077124753022f00cf84fb09df87f66d6bc46f9a61a27d45ff851
 test     | /test                 | 4157af127d56077124753022f00cf84fb09df87f66d6bc46f9a61a27d45ff851
 test     | /test                 | 4157af127d56077124753022f00cf84fb09df87f66d6bc46f9a61a27d45ff851
 test     | /test                 | 4157af127d56077124753022f00cf84fb09df87f66d6bc46f9a61a27d45ff851
 test     | /test                 | 4157af127d56077124753022f00cf84fb09df87f66d6bc46f9a61a27d45ff851
 /        | /                     | 4157af127d56077124753022f00cf84fb09df87f66d6bc46f9a61a27d45ff851

**Comment by cnlangzi** [comment]
it is related to https://github.com/0chain/blobber/issues/329
