### ISSUE TITLE
File upload inside a file

### ISSUE THREAD

**Issue by lpoli** [0chain/blobber#454]
When we upload a file to some remotepath it creates parent directories if they already are not present. So when a file is uploaded say `/a.txt` blobber stores it as file type `f`, which is absolutely fine.

Now when we upload a file say `b.txt` with remotepath `/a.txt/b.txt` then blobber happily accepts it and when we do `zbox list --remotepath /a.txt` we can see `b.txt` in its list. And when we do `zbox list --remotepath /`, it shows `a.txt` with type `f`.

Blobber can provide this feature/issue, but it results in inconsistencies and lots of confusion for other tools and direct user as well.
We should not allow upload inside a file.

**Comment by cnlangzi** [comment]
@lpoli please leave `good first issue` for newcomers if it is possible
