### ISSUE TITLE
toggle permission to  `upload`,`delete`, `update`, `move`, `copy` and `rename`.

### ISSUE THREAD

**Issue by Sriep** [0chain/blobber#476]
There is a new toggle to allow  `upload`,`delete`, `update`, `move`, `copy` and `rename`.

Boolean fields controlling this will be added to the allocation object blobber gets from 0cahin. Each of `upload`,`delete`, `update`, `move`, `copy` and `rename` should only be permitted if the corresponding field in the allocation object permits it.

This change is blocked by https://github.com/0chain/0chain/issues/828.

**Comment by lpoli** [comment]
@Sriep Can you please explain this a bit more with some appropriate links?

**Comment by lawRathod** [comment]
Requires https://github.com/0chain/0chain/pull/1553 to be merged.

**Comment by Sriep** [comment]
We should send the transaction type, upload, delete, update, move, copy or rename to 0chain when committing the transaction. So we need to add this to the write marker.

**Comment by guruhubb** [comment]
We just need 3 different states.
a) default - as in mutable - all crud operations are allowed
b) upload-only, so no updates, rename, copy, move, delete
c) immutable - no cruds are allowed except for reads
@Sriep @lpoli @cnlangzi
