### ISSUE TITLE
Object operation handler's response is not proper

### ISSUE THREAD

**Issue by lpoli** [0chain/blobber#494]
url -> `/v1/file/download/{allocation}`
handler -> `storageHandler.DownloadFile`

Above handler returns value of type `interface{}`. So this means it can be `[]byte` and `some_other_type`. In gosdk to find out if response data is actual data; it is first tried with `json.Unmarshal' and its error is considered along with http status code.

Http status codes should be used properly to communicate error response and data.

**Comment by lpoli** [comment]
cc @cnlangzi

**Comment by cnlangzi** [comment]
@lpoli  yes, almost of apis should be improved with restful api format.

**Comment by cnlangzi** [comment]
it is similar to #470
