### ISSUE TITLE
Track mount/unmount of disk on fly

### ISSUE THREAD

**Issue by lpoli** [0chain/blobber#498]
As we are making progress on storage capacity of blobbers, it is also necessary to have track of mounted and unmounted disk in runtime. So for example, if new disk is mounted to the system for it to store allocation's data, this new capacity needs to be reflected in blockchain as well without blobber going offline. So this is similar to `bl-update` that we do in zboxcli.

We need some goroutine that keeps track of mounts/umounts for storage. It needs to update blobber's capacity to blockchain.

This is also required to have in Sharders as well. When some disk is mounted then it should be able to store blocks in this disk as well, without going offline.

**Comment by lpoli** [comment]
cc @moldis @platsko @guruhubb

**Comment by guruhubb** [comment]
@lpoli is this same as https://github.com/0chain/blobber/issues/523. If so, lets close one of them.

**Comment by lpoli** [comment]
closed #523
