### ISSUE TITLE
Rank of a blobber.

### ISSUE THREAD

**Issue by krishnemd** [0chain/blobber#506]
UI requires some new terms for blobber like:

- Rank,
- commission 
- node diversity
- utilization%  
- quality score% etc 

Do we on Blobber team have some standard definition of these terms already or it is the first time we are defining them ?
As per the UI team the definition for the terminologies is as follows: 

- utilization = used / total_storage
- quality score% = (num_success_challenges/total_challenge)*100

**Comment by lpoli** [comment]
What about the definition of `rank`, `commission` and `node diversity`?
Please explain them as well.

**Comment by ranajahanzaib** [comment]
@chauchausoup is no longer with us, and I joined a few weeks before he left. Our senior lead @shaktals has also left, so I suspect anyone else from the front-end team would know.

For now, I'm marking it `wontfix`. Please, feel free to close it, if needed in the future, we can re-open this issue.
