### ISSUE TITLE
Race condition with read marker

### ISSUE THREAD

**Issue by lpoli** [0chain/blobber#507]
Current ReadMarker structure:
```
type ReadMarker struct {
	ClientID        string           `json:"client_id"`
	ClientPublicKey string           `json:"client_public_key"`
	BlobberID       string           `json:"blobber_id"`
	AllocationID    string           `json:"allocation_id"`
	OwnerID         string           `json:"owner_id"`
	Timestamp       common.Timestamp `json:"timestamp"`
	ReadCounter     int64            `json:"counter"`
	Signature       string           `json:"signature"`
}
```

As per the protocol _**The smart contract will release funds corresponding to the difference between the read_counter in the marker and the latest read_counter redeemed on the blockchain**_

The importance of ReadCounter is only to allow blobber to redeem tokens from read pools. The ReadCounter is based on the assumption that each counter corresponds to 64KB read by the client. So the price calculation is done as: `ΔReadcounter * blockSize * read_price`. 

_Note: BlockSize is customizable with new chunkupload feature so it is no more fixed 64KB._

However above implementation leads to race condition for ReadCounter as readmarker signed by client requires it to be the latest ReadCounter so that blobber can calculate price easily. Blobber code rejects download request if readCounter is not in sync.
```
	if latestRM != nil &&
		latestRM.ReadCounter+(numBlocks) != readMarker.ReadCounter {

		var response = &blobberhttp.DownloadResponse{
			Success:      false,
			LatestRM:     latestRM,
			Path:         fileref.Path,
			AllocationID: fileref.AllocationID,
		}
		return response, nil
	}
```

ReadMarker is associated to client so there won't be race between clients for ReadCounter as they will have their own ReadCounter. However if a client sends multiple download requests, be it for same file or different files, there will be race for latest ReadCounter between requests.

In my view this problem can be solved by replacing ReadCounter with ReadSize and requiring blobber to request read pools with each read marker to redeem read tokens rather than single read marker being able to redeem whole tokens. With this client simply signs readmarker with required size and there is no race for anything.

EDIT:
After successfully merging the above solution, we realized that there is no mechanism against indefinite redeeming of same read marker. `ReadCounter` had served this purpose. So we moved

**Comment by lpoli** [comment]
cc @taustin @guruhubb @Sriep @peterlimg  @moldis @cnlangzi

**Comment by Sriep** [comment]
I suggest doing this in three stages.
1. Blobber: Add the `read_size` field to the ReadMarker.
2. 0cahin: Change to use the `ReadMarker.read_size` field instead of `read_marker` .
3. Optionally Blobber Remove read_marker field.

**Comment by peterlimg** [comment]
LGTM
