### ISSUE TITLE
_stats vs _statsJSON

### ISSUE THREAD

**Issue by krishnemd** [0chain/blobber#508]
UI requires the JSON version of _stats page. At present we do have html  data from the backend but required format is JSON with same data. 
On the other hand _statsJSON is there but the information is limiting.

**Comment by krishnemd** [comment]
As discussed today, UI requires possibly 2 -3  APIs from the present _stats page.

1. Portion above the allocation stats table in one API.
2. Allocations stats portion in one. The API response should not be all the allocations from the table but possibly an aggregation of the column heads.

**Comment by peterlimg** [comment]
Keep the `_stats`, but gives the response base on the http request header. 
Check https://github.com/0chain/0chain/pull/975/files

**Comment by krishnemd** [comment]
@peterlimg isnt the PR focused on miners and sharder ? We also require the same feature for **blobbers** too.

**Comment by samtholiya** [comment]
> On the other hand _statsJSON is there but the information is limiting.

@chauchausoup can you please explain? what is limiting

**Comment by peterlimg** [comment]
@chauchausoup sorry I mean do it like this: https://github.com/0chain/0chain/pull/975/files#diff-ded9fd4e674db371cbbdd16036c8673e7747e122a4caf61f350abbc9054beea8R617

**Comment by guruhubb** [comment]
@shaktals can you take a look at https://github.com/0chain/blobber/issues/508#issuecomment-1039659124

**Comment by shaktals** [comment]
I tried querying https://sculptex.us/blobber51/_stats with header `Accept: application/json` but still received an html response.

**Comment by shaktals** [comment]
Same for https://dev.0chain.net/blobber01/_stats

**Comment by shaktals** [comment]
I'll take a look at the root issue, see if I can solve it.

**Comment by peterlimg** [comment]
@shaktals I think the `Accept: application/json` is what we need to implement.
