### ISSUE TITLE
New description field

### ISSUE THREAD

**Issue by Sriep** [0chain/blobber#514]
Add a new description field to `0chain.blober.yaml`. Pass this to blobber when joining a 0chain network with `add_blobber`.

Works with https://github.com/0chain/0chain/issues/938.

**Comment by Sriep** [comment]
Check here for further details here https://github.com/0chain/0chain/issues/921. We want a name, logo description and reference link.

**Comment by moldis** [comment]
https://github.com/0chain/blobber/pull/606
