### ISSUE TITLE
[Infinite storage] While we attaching new volume - need to call chain

### ISSUE THREAD

**Issue by moldis** [0chain/blobber#523]
While we attaching a new volume - need to call the chain to update storage size for stacking

**Comment by moldis** [comment]
Duplicated https://github.com/0chain/blobber/issues/498

**Comment by jkrus** [comment]
[Update blobbers capacity.pdf](https://github.com/0chain/blobber/files/8138845/Update.blobbers.capacity.pdf)

**Comment by moldis** [comment]
Duplicated https://github.com/0chain/blobber/issues/498
