### ISSUE TITLE
Avoid using default json tag

### ISSUE THREAD

**Issue by lpoli** [0chain/blobber#535]
Check this structure [`Ref`](https://github.com/0chain/blobber/blob/staging/code/go/0chain.net/blobbercore/reference/ref.go#L60). This structure has not used `json` tag and `encoding/json` takes encodes all field names. All fields in json encoding is not required.

Also check other related structure [`paginatedRef`](https://github.com/0chain/blobber/blob/staging/code/go/0chain.net/blobbercore/reference/ref.go#L60). This structure is just created to have `json` tag and to avoid conflicts as it created some field name issue when `json` tag was added to `Ref` struct.

We need to check all structures that will be json encoded and put `json tag` in relevant fields. Comply json tag field name with existing field names so it will not create any issue.

**Comment by moldis** [comment]
Probably this change will broke all system tests, so consider just include 'json:-' to avoid returning useless data in response
