### ISSUE TITLE
[FEATURE] Provide fee for transactions

### ISSUE THREAD

**Issue by Kishan-Dhakan** [0chain/blobber#544]
Blobber/validator makes transactions with 0 fees, it won't work on mainnet.
E.g: 
```
zcntxn, err := zcncore.NewTransaction(txn, 0)
```

Proposal: to use user provided fees and if not provided use `min_fee` as default.

See: 
- https://github.com/0chain/zwalletcli/issues/85
- https://0chain.slack.com/archives/G01FYNN6DK4/p1645097379703449

**Comment by lpoli** [comment]
@moldis Any progress on this?

**Comment by boddumanohar** [comment]
blocked by: https://github.com/0chain/zwalletcli/issues/85
