### ISSUE TITLE
status code 204 should be returned if file is not found in disk

### ISSUE THREAD

**Issue by cnlangzi** [0chain/blobber#556]
check io err `no such file or directory`. status code 204 should be returned like we did on https://github.com/0chain/zboxcli/issues/99

**Comment by princeparmar** [comment]
@cnlangzi Already done
Gosdk : https://github.com/0chain/gosdk/pull/396
zBox : https://github.com/0chain/zboxcli/pull/181
Blobber : https://github.com/0chain/blobber/pull/551

**Comment by cnlangzi** [comment]
a new bug is introduced by 204 on https://github.com/0chain/blobber/issues/385#issuecomment-1069719037

**Comment by cnlangzi** [comment]
waiting for https://github.com/0chain/blobber/issues/592 to merge first.
