### ISSUE TITLE
🐛 Remove isIntegrationTest in main code

### ISSUE THREAD

**Issue by moldis** [0chain/blobber#607]
`if isIntegrationTest {
		fmt.Print("	[SKIP]\n")
	} else {
		if err := handler.WalletRegister(); err != nil {
			fmt.Println(err.Error() + "\n")
			panic(err)
		}
		fmt.Print("	[OK]\n")
	}
`

and following code using variable `isIntegrationTest` which seems strange to me. None of the main codes should know anything about tests.
Consider removing this variable and using proper mocking instead

**Comment by moldis** [comment]
cc @cnlangzi seems from your previous code

**Comment by cnlangzi** [comment]
I think it was introduced by grpc team. @kushthedude  could you check it?

**Comment by cnlangzi** [comment]
@Shrhawk  it is related to https://github.com/0chain/blobber/issues/253. please check it too

**Comment by lpoli** [comment]
@moldis Isn't is like having `production` or `development` flag?

**Comment by moldis** [comment]
@lpoli @cnlangzi The main code should never know about any testing. This frag should be removed and included proper integration testing, it seems previous developer just tried to simplify his life.
And `production` or `development` flags are for `logs` purpose mostly, not related to any tests

**Comment by avanaur** [comment]
@cnlangzi is this part of conductor testing where the main binary is built for integration test?

It seems there is `integration` env var is expected instead of just having `integration_tests` build flag. I can remove that env var check and refactor to using the build flag. Is there a change elsewhere needed where that `integration` env var is set and perhaps building the binary without the build flag?

**Comment by cnlangzi** [comment]
@avanaur  there are two tests that is named `integration-*` by different developers. it is confused now
- https://github.com/0chain/blobber/blob/902adcfc57eb8773f9874e8645ee2ae645848ded/.github/workflows/tests.yml#L64
- https://github.com/0chain/0chain/blob/d1cd42944494bc5d85e5d1fa4b46580ea245a336/.github/workflows/build-conductor-blobber-test.yml#L89
I would suggest to improve naming for them. 1st is intergration-tests for blobber+postgres,  2nd is conductor test for blockchain+blobber.

by the way,  it is better if we migrate current 1st integration-tests to unit tests as https://github.com/0chain/blobber/issues/253 mentions. 

I think grpc team didn't how to test it without postgres, that is why it was implemented based on docer+postgres.

**Comment by cnlangzi** [comment]
I think @moldis doesn't know it very well, so please feel free to improve them with any better way.

**Comment by cnlangzi** [comment]
FYI: https://github.com/0chain/blobber/issues/653 and https://github.com/0chain/blobber/issues/398

**Comment by avanaur** [comment]
@cnlangzi just to set the expectation on this ticket. 

I will convert the local integration/component tests to unit tests so there is no need to start blobber with `integration=1` env var. There seems to be 16 tests affected so porting may take a while as I may need to understand how each test works.

We can still go with just moving over test codes living on productions codes to their own respective files restricted with build flag like `component_test`. This would be the simpler approach.

But will proceed with the conversion as that seems the preference.
