### ISSUE TITLE
Challenges not getting stored in db

### ISSUE THREAD

**Issue by ssardana08** [0chain/blobber#641]
- Blobber has challenges generated by chain, but not getting stored in blobber db.
- On debugging, found the issue while [decoding /openchallenges response](https://github.com/0chain/blobber/blob/9d6fe7b078eb40d7759b9e70f06ee8e977e1e4ca/code/go/0chain.net/blobbercore/challenge/challenge.go#L49)

**Comment by cnlangzi** [comment]
@sum-it08  it should be fixed on #645 ,please check it again.

**Comment by ssardana08** [comment]
there were decoding error too, fixed with https://github.com/0chain/0chain/pull/1189

**Comment by peterlimg** [comment]
@sum-it08 is PR #645 fixed this issue?

**Comment by ssardana08** [comment]
@peterlimg #645 fixed one part.
There is another part of the code where decoding issue happened. I have linked a PR to it.. it will go along with challenge PR of 0chain.
This issue should be closed with generate challenge infinite issue..
