### ISSUE TITLE
Blobber conductor tests.

### ISSUE THREAD

**Issue by service-0chain** [0chain/blobber#653]
These tests will be written/modified by Roman or Dabasov Yuri.

- [x] Configure a separate server as a github runner.

- [x] Create its github actions to run these whenever required.

- [x] Run these github actions automatically on daily basis.

- [x] Add these tests as a checkpoint before merging the pull requests.

**Comment by rrrooommmaaa** [comment]
as soon as https://github.com/0chain/0chain/pull/644 is merged,
the building steps described in https://github.com/0chain/0chain/blob/d9a3398e8a6c78344621c9487a10e64571233d6c/code/go/0chain.net/conductor/README.md can be used to automate gha

**Comment by service-0chain** [comment]
@rrrooommmaaa 
gitactions are created and pushed to `staging` but blobber gh is failing due to `pull access denied for blobber_base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`.

last gitaction --> https://github.com/0chain/0chain/runs/6322207695?check_suite_focus=true

**Comment by service-0chain** [comment]
@rrrooommmaaa 
gitactions are created and pushed to `staging` but blobber gh is failing due to `pull access denied for blobber_base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`.

last gitaction --> https://github.com/0chain/0chain/runs/6322207695?check_suite_focus=true

**Comment by service-0chain** [comment]
@cnlangzi 
@rrrooommmaaa had created the conductor tests & @m-s-a-c  have created gitactions for performing blobber conductor test. But conductor tests are failing due to some blobber issue as reprted by @rrrooommmaaa. 

gh actions --> https://github.com/0chain/0chain/actions/workflows/conductor-blobber-tests.yml

After every run report is uploaded over to the gh action run. You can check it for analysing the errors.

**Comment by cnlangzi** [comment]
run `./docker.local/bin/build.base.sh` to build `blobber_base` docker image first. it will be fixed.

**Comment by service-0chain** [comment]
@cnlangzi 
we are already running this to build `blobber_base`
