### ISSUE TITLE
[Question] Is it really worth it to write unit tests at the moment for grpc endpoints?

### ISSUE THREAD

**Issue by shravanshetty1** [0chain/blobber#67]
For us to unit test everything, we will have to write test code equal or slightly more than the amount of production code. This code has to be maintained as the underlying code base changes and is also time consuming to write.

Meanwhile with end to end/integration testing we can get much higher efficiency. For nearly 100 lines of testcode we could expect 10000 lines of production code to be tested.

Also since the amount of unit test code will be so large, how do we know the testing code works as expected? Do we write unit tests to test the tests?

The only pro i can think of is it promotes better quality of code since it will force modularity(due to mocks) to test the code. 

Please share your thoughts, this seems overly inefficient to me.

**Comment by Sriep** [comment]
By auto running unit tests as part of CI, they stop regressions. If any modification breaks a method with unit tests then the unit tests should break, alerting the world to the problem. End to end tests, while necessary, are not as fine-tuned to each function they pass through.

End to end testing will always touch more code than unit tests. A unit test just focuses on one method, confirming its input and outputs. End to end tests, work on used cases. I am not sure your lines of code metric is comparing like with like.

Testing code being larger than the code being tested is not I think an issue and quite normal. An agile framework survives on the quality of its tests. 

What might be more of a problem is if the tests need to be constantly updated. But are storage_handler.go, object_operation_handler.go, grpcMiddleware.go, grpchandler.go and conver.go aregoing to be constantly updated? Once the grpc development is over I would expect they would not change much, all the changes being in the auto-generated files.

Don't try to force the unit tests to do the same thing as an integration test. Just confirm they perform as expected in simple mocked out situations.
