### ISSUE TITLE
fix security issues suggested by code-scanning

### ISSUE THREAD

**Issue by cnlangzi** [0chain/blobber#670]
see detail https://github.com/0chain/blobber/security

**Comment by Manish-210** [comment]
@cnlangzi 
I think code scanning needs to be enabled so that we can view the security issues. Do you have the write permissions?
https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning-for-a-repository

**Comment by dabasov** [comment]
https://github.com/0chain/blobber/security/code-scanning
