### ISSUE TITLE
Change github hosted runner to self hosted runners.

### ISSUE THREAD

**Issue by service-0chain** [0chain/blobber#674]
@cnlangzi 
kindly replace the github runner with self hosted runners --> https://github.com/0chain/blobber/blob/902adcfc57eb8773f9874e8645ee2ae645848ded/.github/workflows/tests.yml#L66
Tags that can be used for self hosted runners are as `self-hosted`

**Comment by cnlangzi** [comment]
@service-0chain  `integration-tests` didn't work properly on `self-hosted`. that is why it is `ubuntu-20.04`. I will try to test it again.

**Comment by service-0chain** [comment]
if it fails please tag @m-s-a-c to look into it.
