### ISSUE TITLE
panicking issue on automigration

### ISSUE THREAD

**Issue by cnlangzi** [0chain/blobber#687]
if skip `db.Migrator().DropTable(tableName)`, migration panics

<img width="1460" alt="Screen Shot 2022-05-20 at 15 04 43" src="https://user-images.githubusercontent.com/347651/169472395-0106fd9c-7e57-460e-8169-b4b7f9edd3d4.png">

**Comment by lpoli** [comment]
Fixed by https://github.com/0chain/blobber/pull/705
