### ISSUE TITLE
it is not good to drop all tables on startup

### ISSUE THREAD

**Issue by cnlangzi** [0chain/blobber#697]
based on the logic, it has to be configured on 0chain_blobber.yml if a new table should not be dropped on startup. but 0chain_blobber.yml is not managed by blobber repo, is managed by 0helm with deveops team.  for 3rd blobber services , it is managed by its provider. so it is impossible to update/add it by developer. 

It is better to keep all tables as default behavior. if not, all data will be lost if a blobber is restarted.

https://github.com/0chain/blobber/blob/845a97e4d0c2049e8b3b2c963baecd513fdad841/code/go/0chain.net/blobbercore/automigration/automigration.go#L133

<img width="1319" alt="Screen Shot 2022-05-27 at 15 50 33" src="https://user-images.githubusercontent.com/347651/170655489-9c307775-5498-44e1-a139-473eaf4e0850.png">

**Comment by cnlangzi** [comment]
there are 3 user-cases that need to be clarified how they work
- tables are configured to keep on yml file. how it works if any table should be migrated(eg add new columns , drop some old columns). 
- tables are not configured to keep on yml file. how to keep blobber's data safe if server/blobber is restarted
- how to let blobber knows which table should be configured, or not? eg a new table is added by developer, and it should be configured or not?

as we know, blobber is released as docker image without any yml configuration file. the yml configuration file is managed by server owner.
and increase sql scripts have be removed completely from blobber repo now. who are responsible for database migration for blobber owner? and how it works?

**Comment by lpoli** [comment]
Fixed by https://github.com/0chain/blobber/pull/705
