### ISSUE TITLE
List endpoint only works on directories 

### ISSUE THREAD

**Issue by stewartie4** [0chain/blobber#699]
When calling list with a filepath pointing to a file, an empty result is always returned.
However calling list with a filepath pointing to directory, the results are returned as expected

Is list only intended for directories (as opposed to the ls command in unix which supports files and directories for example)

If so, this needs to be made clear as it is confusing as-is

**Comment by avanaur** [comment]
@peterlimg @cnlangzi should we support non-directory on `zbox list`? I am thinking no and we can simply indicate on `zbox list` that it expects the `--remotePath` provided is a folder and will try to list contents. Same for `--authticket` param.

```
./zbox list --help
list files from blobbers

Usage:
  zbox list [flags]

Flags:
      --allocation string   Allocation ID
      --authticket string   Auth ticket fot the file to download if you dont own it
  -h, --help                help for list
      --json                pass this option to print response as json data
      --lookuphash string   The remote lookuphash of the object retrieved from the list
      --remotepath string   Remote path to list from
```

If there are no concerns, I'll raise a PR to update the `list` description and the description of the params mentioned.

**Comment by peterlimg** [comment]
@avanaur I think we need to return the file if the `remotePath` points to a file.
