### ISSUE TITLE
Need to add extra field to files table "starred" true/false

### ISSUE THREAD

**Issue by moldis** [0chain/blobber#700]
We need it in frontend to star/unstar file and display in favorites view. Apply on both files and folders

**Comment by avanaur** [comment]
@cnlangzi @moldis 

Got clarifications:
- Should this `starred` attribute be on a  file-level such that it appears as `starred` for any client or this would be a client and file combination like a personal preferences? At the moment, I assume the former.
- Are both owner and collaborators allowed to update this `starred` value? I assumed only owner can update given this apply on file-level.
- Is changing the value gonna required hash recalculation? I assumed not as the column is for UI preferences only.
- For the listing capability, does this retrieve all starred files/folders regardless of their paths? Or will this be a filter on `list folder contents` (`/v1/file/list/{allocation}`) endpoint to show only starred files/folders that are immediate children? I assume this will be regardless of paths.
- Will the listing of starred files/folders require some pagination at this point? It seems `list folder contents` endpoint do not limit yet so this is likely that too for now.

**Comment by guruhubb** [comment]
Responses below:

- Its file-level attribute, so allocation can change ownership and it won't affect it.
- owner
- correct, no hash change
- yes regardless of paths 
- yes we should paginate in the future, so raise it separately as a post-main net issue

**Comment by sculptex** [comment]
First point, for file-level starred function to work on any client sounds like it would require dB entry on blobbers with high performance impact 

I am pretty sure this should be independent on a client basis, to implement on backend that manifested all clients would open up a huge can of worms.

**Comment by sculptex** [comment]
@guruhubb this will have terrible impact on blobber dB, is basically order of magnitude worse than list-all

**Comment by lpoli** [comment]
We cannot have client specific starring. Allocation owner can specify their files/dirs to be starred but I don't see significance of starring.
Also I don't think we are ready to do this in current blobber's architecture.

**Comment by avanaur** [comment]
⚠️ This is currently halted. From offline discussion, this functionality is not best to have on blobber. Alternative solution is currently considered.

**Comment by avanaur** [comment]
.

**Comment by lpoli** [comment]
@avanaur 
What is happening with this issue?
It needs to be done in gosdk.
Are you on it?
