### ISSUE TITLE
Finalize Allocation is broken

### ISSUE THREAD

**Issue by stewartie4** [0chain/blobber#704]
Not sure if this issue belongs on the blobber side or with the CLI:
Finalizing an allocation seems broken with the error message:
Error finalizing allocation:fini_alloc_failed: allocation is not expired yet, or waiting a challenge completion

Steps to reproduce:
- Create an allocation
- Wait for the allocation to expire, or manually expire it early 
- Run ./zbox alloc-fini

**Comment by cnlangzi** [comment]
it might be blocked by `waiting a challenge completion`. for now, challenge will be generated in every round. it might be the problem. Blobber might be picked up to pass challenge in every round.  because there are only 6 blobbers in our test networks. cc @peterlimg  @sum-it08

**Comment by peterlimg** [comment]
This error is reported when the finalize txn timestamp value is less than the `allocation expiration time + the challenge completion time`. so if the default challenge completion time is 3m, then we will see this error in 3m after we expired the allocation manually. Please wait till the challenge completition time is passed, and see if still have the error.

**Comment by stewartie4** [comment]
Thanks for this guys, I'll tweak the test and report back

**Comment by stewartie4** [comment]
Thanks for this, all seems to be working correctly after waiting for max challenge time 
Closing this issue.
