### ISSUE TITLE
ChallengeCompletionTime should be removed from Terms on blobber registration

### ISSUE THREAD

**Issue by cnlangzi** [0chain/blobber#719]
related to https://github.com/0chain/0chain/issues/1369

discussion on https://0chain.slack.com/archives/C03788G8N2D/p1654621796262099

**Comment by peterlimg** [comment]
duplicate with https://github.com/0chain/0chain/issues/1230

**Comment by cnlangzi** [comment]
@peterlimg  https://github.com/0chain/0chain/issues/1369 is duplicated with https://github.com/0chain/0chain/issues/1230 . leave this issue to fix blobber code
