### ISSUE TITLE
Download fails if one blobber is down

### ISSUE THREAD

**Issue by fabioDMFerreira** [0chain/blobber#780]
**Steps**

1. Launch 1 sharder and 3 miners;
2. Start 0dns
3. Launch 3 blobbers
4. Initialize allocation
5. Upload 1 file
5. Stop 1 of the blobbers
6. Download 1 file

You can easily replicate this using the conductor test `blobber-1`.

**Actual**

Download fails with the next error
```
0box-sdk        [ERROR]  2022/08/04 15:16:26.432772 filemetaworker.go:128: File consensus not found for /remote/random.bin
Error in file operation: No minimum consensus for file meta data of file
```

**Expected**

Download the file with success.

**Comment by lpoli** [comment]
Can you also specify data/parity ratio and size of file?

**Comment by fabioDMFerreira** [comment]
This is the command used to create the allocation
```
./zboxcli/zbox --wallet testing.json newallocation \
    --read_price 0.001-10 --write_price 0.01-10 --size 104857600 --lock 4 \
    --data 2 --parity 1 --expire 48h
```

I guess the answer is 2 for data and 1 for parity ratio. The size of the file is 5 MB.

**Comment by sculptex** [comment]
@fabioDMFerreira did you check the remaining 2 blobbers included in that allocation are operational? It should show in debug output if you don't specify --silent

**Comment by fabioDMFerreira** [comment]
@sculptex yes, the remaining blobbers were operational. I just ran the test again and I have logs in my machine I can share.

I found the next error in both blobbers logs. Wondering if it is useful.
```
[35mblobber_1        |[0m 2022-08-08T13:28:08.271Z	ERROR	challenge/challenge.go:42	[challenge]open: 	{"error": "[txn] too less sharders to confirm it: min_confirmation is 50%, but got 0/2 sharders\r\nGet \"http://198.18.0.82:7172/v1/screst/6dba10422e368813802877a85039d3985d96760ed844092319743fb3a76712d7/openchallenges?blobber=7a90e6790bcd3d78422d7a230390edc102870fe58c15472073922024985b1c7d\": dial tcp 198.18.0.82:7172: connect: no route to host\r\nGet \"http://198.18.0.81:7171/v1/screst/6dba10422e368813802877a85039d3985d96760ed844092319743fb3a76712d7/openchallenges?blobber=7a90e6790bcd3d78422d7a230390edc102870fe58c15472073922024985b1c7d\": dial tcp 198.18.0.81:7171: connect: no route to host"}
[35mblobber_1        |[0m github.com/0chain/blobber/code/go/0chain.net/blobbercore/challenge.syncOpenChallenges
[35mblobber_1        |[0m 	/blobber/code/go/0chain.net/blobbercore/challenge/challenge.go:42
[35mblobber_1        |[0m github.com/0chain/blobber/code/go/0chain.net/blobbercore/challenge.startSyncOpen
[35mblobber_1        |[0m 	/blobber/code/go/0chain.net/blobbercore/challenge/worker.go:46
```

**Comment by lpoli** [comment]
It is always required to be able to get data from `data + 1` number of blobbers. In above case `data` is 2 and `parity` is 1. In total of 3 blobbers if one fails, then we are not able to get data from `data + 1` number of blobbers. 
So failing in this case is normal.

**Comment by fabioDMFerreira** [comment]
@lpoli Shouldn't `data + 1` blobbers be needed only for uploads? 

The existing conductor test seems to expect download to succeed if only 2 blobbers are available (if data shards = 2 and parity = 1), but expects the upload to fail because consensus should reach at least 76.6%. 

However, if the formula `data + 1` is applied to download and upload and I will change the test accordingly.

cc @dabasov
