### ISSUE TITLE
Unable to upload after a blobber has stopped

### ISSUE THREAD

**Issue by fabioDMFerreira** [0chain/blobber#791]
**Steps**
1. Launch 1 sharder and 3 miners;
2. Start 0dns
3. Launch 4 blobbers
4. Stake tokens on the 4 blobbers
5. Upload file and then remove it
6. Stop one of the blobbers
7. Upload file (`./zboxcli/zbox --wallet testing.json upload \
    --allocation "$(cat ~/.zcn/allocation.txt)" \
    --localpath="$(pwd)/testrepair/repair1.bin" \
    --remotepath=/remote/repair/repair1.bin`)

**Expected**
I expected the file to be uploaded with success.

**Actual** 
The next error shows up while uploading the file
```
0box-sdk        [ERROR]  2022/08/08 17:30:15.694326 chunked_upload_blobber.go:67: Upload : Post "http://198.18.0.94:5054/v1/file/upload/c611d70aab1a846891a277fa1f911ba850c86fb0415d7adf9fa8d619f6588a14": dial tcp 198.18.0.94:5054: connect: no route to host
0 / 10485760 [---------------------------------------------------------------------------------------------------------------------------------]   0.00% 18s
Error in file operation: Post "http://198.18.0.94:5054/v1/file/upload/c611d70aab1a846891a277fa1f911ba850c86fb0415d7adf9fa8d619f6588a14": dial tcp 198.18.0.94:5054: connect: no route to host
Upload failed. Post "http://198.18.0.94:5054/v1/file/upload/c611d70aab1a846891a277fa1f911ba850c86fb0415d7adf9fa8d619f6588a14": dial tcp 198.18.0.94:5054: connect: no route to host
```

**Comment by fabioDMFerreira** [comment]
Prob. this a zbox problem and not a blobber problem. If one of the blobber is unreachable we should just skip the uploading of the file to this service.

**Comment by lpoli** [comment]
Fixed by https://github.com/0chain/gosdk/pull/558
