### ISSUE TITLE
Mock out gorm.DB to allow blobber unit tests

### ISSUE THREAD

**Issue by Sriep** [0chain/blobber#81]
Currently it's not easy to write unit tests as blbber uses a raw gorm.DB in the code. It is generally bad to use active databases in unit tests, they should be mocked out. However, the way the blobber is written this is difficult to impossible.

The gorm.DB should be wrapped in an interface to make it easer to mock.

**Comment by Sriep** [comment]
https://github.com/0chain/blobber/pull/87

**Comment by shravanshetty1** [comment]
@Sriep What do you think about creating a store layer module.

This will make it easy to swap out underlying database at any time as long as the store interface has been implemented by the new database.
This will make it even easier to test as adding sqlmock is tedious.
