### ISSUE TITLE
Capacity is updated by itself and not by config file

### ISSUE THREAD

**Issue by Manali-Jain-squareops** [0chain/blobber#817]
- the capacity i have given to blobbers capacity: 10737418240  which is 10GiB
- for few minutes diagnostics page showed 10GiB
- but after some time on diagnostics page it is showing some other value and this same value is visible on CLI as well
![image](https://user-images.githubusercontent.com/86873900/187647777-0d049e40-562d-4a3e-bb2c-2ea09ce5b725.png)
![image](https://user-images.githubusercontent.com/86873900/187647819-8ae6cc8a-bce9-4ee9-8e3b-b2a6e8990d96.png)
![image](https://user-images.githubusercontent.com/86873900/187647885-867d7cf4-f70c-412d-858c-a19a6815a802.png)

**Comment by boddumanohar** [comment]
closing this as this is the expected behaviour
