### ISSUE TITLE
Search endpoint to get file details/metadata using lookupHash

### ISSUE THREAD

**Issue by lawRathod** [0chain/blobber#820]
* We have ability to list files part of the allocation using `listObjects` available on gosdk. 
* The object in the response of `listObject` contains file details/metadata info.
* Using lookupHash we would like to get any file's details from a REST endpoint. 
* Not sure but maybe we could add this to gosdk too.

**Comment by boddumanohar** [comment]
we store name in FileMetaData if we want search similar to SQL` LIKE` we need to index it somehow for full text search index.
we can try this, not sure how much overhead will it create, we can investigate https://www.postgresql.org/docs/current/textsearch-tables.html#TEXTSEARCH-TABLES-INDEX
