### ISSUE TITLE
New move file endpoint

### ISSUE THREAD

**Issue by Sriep** [0chain/blobber#852]
We need a new `move` file endpoint that moves a file without charging.

Currently g[oSDK.zboxcore.sdk.allocation.MoveOject](https://github.com/0chain/gosdk/blob/staging/zboxcore/sdk/allocation.go#L933)
```go
func (a *Allocation) MoveObject(path string, destPath string) error {
	err := a.CopyObject(path, destPath)
	if err != nil {
		return err
	}
	return a.DeleteFile(path)
}
```

However, a `copy` charges, so `copy` and `delete` cannot be used instead of the free `move` action.

Add[ new handler to blobbercore](https://github.com/0chain/blobber/blob/staging/code/go/0chain.net/blobbercore/handler/handler.go#L117).

Once we have the new `move` endpoint we will need to update the goSDK file linked above.

**Comment by lpoli** [comment]
@guruhubb Please comment on this
