### ISSUE TITLE
Content-Type should be application/json for blobber REST APIs

### ISSUE THREAD

**Issue by boddumanohar** [0chain/blobber#883]
all the blobber REST APIs are defined in this function

https://github.com/0chain/blobber/blob/36577b69ec02f66049acb7cd6d1959eb7915edab/code/go/0chain.net/blobbercore/handler/handler.go#L117

When a request is made to made to any of these endpoints, in the response headers, the content type is shown as `text/plain` But the expected Content-Type is application/json

step to reproduce:

```
curl -v -X GET https://demo.0chain.net/blobber05//v1/file/meta/262b49e4c60a780bdf8e80aa940bfbb0409533c37af6f313446e15d33d6b109e
```

In the response headers you will observe that the Content-Type is shown as `text/plain`

```
< HTTP/2 400
< date: Mon, 21 Nov 2022 18:27:55 GMT
< content-type: text/plain; charset=utf-8
< content-length: 221
```

**Comment by pgrudra** [comment]
```
// Helper handlers

// Error replies to the request with the specified error message and HTTP code.
// It does not otherwise end the request; the caller should ensure no further
// writes are done to w.
// The error message should be plain text.
func Error(w ResponseWriter, error string, code int) {
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Header().Set("X-Content-Type-Options", "nosniff")
	w.WriteHeader(code)
	fmt.Fprintln(w, error)
}
```
the response @boddumanohar mentioned is for Error with code 400. The inbuilt function http.Error() has been used in the repo for Error responses, and as you can see in the code block, its Content-Type is set to text/plain.
In the PR I have raised(https://github.com/0chain/blobber/pull/946), I have removed use of http.Error()
cc @dabasov
