### ISSUE TITLE
Redundant use of `RequestContext` in all methods in Blobber service

### ISSUE THREAD

**Issue by Shivam010** [0chain/blobber#89]
I think there is no need of using a separate `RequestContext` field in all the requests. We can easily allow certain headers using `ServeMuxOptions` and get them in the request context.

Ref: https://github.com/0chain/blobber/blob/master/code/go/0chain.net/blobbercore/blobbergrpc/proto/blobber.proto#L48

**Comment by Shivam010** [comment]
@shravanshetty1 @Sriep 
I have made the corresponding changes for `GetAllocation` and `GetFileMetaData` for review so that I can change all methods.

**Comment by shravanshetty1** [comment]
for reference - https://github.com/grpc/grpc-go/blob/master/Documentation/grpc-metadata.md
