### ISSUE TITLE
Need a new API that would provide details similar to blobber _stats 

### ISSUE THREAD

**Issue by sagchain** [0chain/blobber#896]
e.g. minimum information would be total capacity, allocated capacity, used storage, open/closed challenges, challenge response time, temporary data stored, number of allocations, number of files

But ideally we need all data points that are part of current blobber_Stats URL

**Comment by sagchain** [comment]
![image](https://user-images.githubusercontent.com/99322536/209077839-40c7e5c1-32d1-4be2-bbab-900ad61010d7.png)

**Comment by boddumanohar** [comment]
@sagchain  we could add to existing blobber stats API, 
can you please list down the additional fields that you would like to be added. I can raise a PR for that.

**Comment by realrisman** [comment]
I will close the issue, since the API is ready on this endpoint /_statsJSON
