### ISSUE TITLE
Blobber: Option to change read and write price through UI

### ISSUE THREAD

**Issue by sagchain** [0chain/blobber#921]

**Comment by sagchain** [comment]
We should provide blobbers an option to change the write price if they want. 

Detailed discussion:  https://0chain.slack.com/archives/C04H2N3FQ92/p1673420360733769

**Comment by boddumanohar** [comment]
to update blobber settings from cli, one can use: 

```
zbox bl-update --blobber_id f65af5d64000c7cd2883f4910eb69086f9d6e6635c744e62afcfab58b938ee25 --read_price 1.0 --write_price 1.2 --min_stake 1.0 --max_stake 5.0
```

which internally send smart contract transaction `update_blobber_settings`

**Comment by realrisman** [comment]
@cnlangzi can you confirm if we have this functionality on wasm? if not we need to create it either on wasm or 0box.

cc: @sagchain

**Comment by cnlangzi** [comment]
It is not exposed yet. Let’s add it in wasm sdk

**Comment by boddumanohar** [comment]
all infrastructure are ready, you can just export it via `jsbridge.BindAsyncFuncs`
see examples: https://github.com/0chain/gosdk/blob/7140de11080e5b2e45fd6545a0fb662b77fd713f/wasmsdk/proxy.go#L131

**Comment by sagchain** [comment]
@cnlangzi will you update once adding it to wasm?

**Comment by boddumanohar** [comment]
@sagchain will raise a PR today 👍
