### ISSUE TITLE
Blobber filter out expired challenges.

### ISSUE THREAD

**Issue by Sriep** [0chain/blobber#93]
The blobber should not waste time trying to resolve expired challenges. Filter out the expired challenges from the challenges sent by the 0chain `/openchallenges` call.

**Comment by Sriep** [comment]
Update FindChallenge in worker.go. The filtering can be added to the [code following the API call](https://github.com/0chain/blobber/blob/master/code/go/0chain.net/blobbercore/challenge/worker.go#L204). 

Write a unit test to confirm the filtering is working ok.

**Comment by andrenerd** [comment]
@Sriep 
How to determine if a challenge is expired or not? Looks like there is no timestamp or status field to be based on.

**Comment by Sriep** [comment]
The expieration is in 0cahin_blobber.yaml.challenge_completion_time. If `Created` plus `challenge_completion_time` has passed then the challenge can be filtered out.

**Comment by andrenerd** [comment]
@Sriep 
updated. please, review the pr:
https://github.com/0chain/blobber/pull/125
