### ISSUE TITLE
Image build process is extremely slow

### ISSUE THREAD

**Issue by peterlimg** [0chain/blobber#964]
The blobber and validator image build process is slow, it takes about 20m to build blobber, 23m for validator
<img width="328" alt="image" src="https://user-images.githubusercontent.com/54137706/221384737-88e97c68-5acb-45f2-a1d7-77c671bcd707.png">

**Comment by Manali-Jain-squareops** [comment]
![image](https://user-images.githubusercontent.com/86873900/221481821-1af8bea4-a3ff-42a5-ae60-074e3c7e94b8.png)
raised PR https://github.com/0chain/blobber/pull/969
