### ISSUE TITLE
Need to capture host name of a blobber in the DB to be used on Atlus

### ISSUE THREAD

**Issue by sagchain** [0chain/blobber#968]
Details here: https://0chain.slack.com/archives/C03ER2LFMEF/p1677088954107519

**Comment by dabasov** [comment]
should be fixed in UI

**Comment by dabasov** [comment]
duplicates [Custom icon and website link on blobbers/miners/sharders config, and ability for clients to read it](https://github.com/0chain/0box/issues/255)
