### ISSUE TITLE
empty build_tag for validators

### ISSUE THREAD

**Issue by boddumanohar** [0chain/blobber#981]
for example when you take a look at this validator

https://demo1.zus.network/validator02/

Build tag is shown empty

<img width="700" alt="Screenshot 2023-03-05 at 09 55 07" src="https://user-images.githubusercontent.com/9148277/222951144-3f2dd5bd-ea4d-49db-9581-b4db37d494f5.png">

**Comment by Manali-Jain-squareops** [comment]
https://github.com/0chain/blobber/pull/983

**Comment by Manali-Jain-squareops** [comment]
![image](https://user-images.githubusercontent.com/86873900/223040139-5a5a497d-cea6-4481-8602-414cc2f1780f.png)
